server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:app}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:app}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}  # Use 'create' for fresh schema each run
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${DB_SHOW_SQL:true}
        format_sql: ${DB_FORMAT_SQL:true}
        use_sql_comments: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        default_schema: notification  # Apply to all JPA entities unless overridden
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
    open-in-view: false

  sql:
    init:
      mode: always  # Run schema.sql at startup (optional)
      platform: postgres

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: ${QUARTZ_JOB_STORE_IS_CLUSTERED:true}
            useProperties: ${QUARTZ_JOB_STORE_USE_PROPERTIES:true}
            tablePrefix: "notification.QRTZ_"  # Note the quotes and schema prefix

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.hbm2ddl: DEBUG
